services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: quanlyquannuoc
      MYSQL_DATABASE: quanlyquannuoc
      TZ: "Asia/Ho_Chi_Minh"
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  mysql_data:
